apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-example
  annotations:
    foo: bar2
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-backend
  target:
    name: secret-to-be-created
  dataFrom:
  - extract:
      metadataPolicy: Fetch
      key: my-secret-tags
  data:
  - secretKey: test
    remoteRef:
      metadataPolicy: Fetch
      key: my-secret-tags
      property: test.json
