apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: backend
  target:
    name: secret-to-be-created
  data:
  - remoteRef:
      key: my-secret
    secretKey: foo
  dataFrom:
  - find:
      name: 
        regexp: secret