apiVersion: external-secrets.io/v1alpha1
kind: SecretSink
metadata:
  name: "hello-world"
  namespace: default # Same of the SecretStores
spec:
  secretStoreRefs:
  - name: secretstore-sample
    kind: SecretStore
  selector:
    secret:
      name: foobar
  data:
  - match:
     - secretKey: foobar
       remoteRefs:
       - remoteKey: my/path/foobar 