apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "hello-world"
spec:
  externalSecretName: "hello-world-es"
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: ["foo","bar","default"]
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: secretstore-sample
      kind: ClusterSecretStore
    data:
      - secretKey: secret-key-to-be-managed
        remoteRef:
          key: /foo/bar
