apiVersion: external-secrets.io/v1beta1   
kind: SecretStore
metadata:
  name: aws-invalid-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: key
            namespace: default
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret
            namespace: default
---
apiVersion: external-secrets.io/v1beta1   
kind: SecretStore
metadata:
  name: aws-valid-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: key
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret