apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invalid-deletion-policy
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: docker-registry
    creationPolicy: None
    deletionPolicy: Delete
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .mysecret }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: foo/broken
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valid-deletion-policy
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: ClusterSecretStore
  target:
    name: docker-registry-no-template
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .mysecret }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: foo/broken