apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: default
data:
  token: cm9vdA== # "root"
---
 apiVersion: external-secrets.io/v1beta1
 kind: ClusterSecretStore
 metadata:
   name: vault-backend
 spec:
   provider:
     vault:
       server: "http://vault.vault:8200"
       path: "kv"
       version: "v2"
       auth:
         tokenSecretRef:
           name: "vault-token"
           key: "token" 
---
 apiVersion: external-secrets.io/v1beta1
 kind: ExternalSecret
 metadata:
   name: vault-example
   namespace: default
 spec:
   secretStoreRef:
     name: vault-backend
     kind: ClusterSecretStore
   target:
     name: example-sync
   data:
   - secretKey: foobar
     remoteRef:
       key: path/to/my/secret
       property: password
---
 apiVersion: external-secrets.io/v1beta1
 kind: ExternalSecret
 metadata:
   name: vault-example
   namespace: another
 spec:
   secretStoreRef:
     name: vault-backend
     kind: ClusterSecretStore
   target:
     name: example-sync
   data:
   - secretKey: foobar
     remoteRef:
       key: path/to/my/secret
       property: password