apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: my-key
    remoteRef:
      property: test
  - secretKey: complete
    remoteRef:
  dataFrom:
  - extract: 
      property: test
