apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        value: '{"ConfigVersion":3,"Driver":{"IPAddress":"mywindowsdocker.northeurope.cloudapp.azure.com","MachineName":"mywindowsdocker","SSHUser":"none","SSHPort":3389,"SSHKeyPath":"","StorePath":"/Users/stefan/.docker/machine","SwarmMaster":false,"SwarmHost":"","SwarmDiscovery":"","EnginePort":2376,"SSHKey":""},"DriverName":"generic","HostOptions":{"Driver":"","Memory":0,"Disk":0,"EngineOptions":{"ArbitraryFlags":[],"Dns":null,"GraphDir":"","Env":[],"Ipv6":false,"InsecureRegistry":[],"Labels":[],"LogLevel":"","StorageDriver":"","SelinuxEnabled":false,"TlsVerify":true,"RegistryMirror":[],"InstallURL":"https://get.docker.com"},"SwarmOptions":{"IsSwarm":false,"Address":"","Discovery":"","Agent":false,"Master":false,"Host":"tcp://0.0.0.0:3376","Image":"swarm:latest","Strategy":"spread","Heartbeat":0,"Overcommit":0,"ArbitraryFlags":[],"ArbitraryJoinFlags":[],"Env":null,"IsExperimental":false},"AuthOptions":{"CertDir":"/Users/stefan/.docker/machine/machines/mywindowsdocker","CaCertPath":"/Users/stefan/.docker/machine/machines/mywindowsdocker/ca.pem","CaPrivateKeyPath":"/Users/stefan/.docker/machine/machines/mywindowsdocker/ca-key.pem","CaCertRemotePath":"","ServerCertPath":"/Users/stefan/.docker/machine/machines/mywindowsdocker/server.pem","ServerKeyPath":"/Users/stefan/.docker/machine/machines/mywindowsdocker/server-key.pem","ClientKeyPath":"/Users/stefan/.docker/machine/machines/mywindowsdocker/key.pem","ServerCertRemotePath":"","ServerKeyRemotePath":"","ClientCertPath":"/Users/stefan/.docker/machine/machines/mywindowsdocker/cert.pem","ServerCertSANs":[],"StorePath":"/Users/stefan/.docker/machine/machines/mywindowsdocker"}},"Name":"mywindowsdocker"}'
      - key: "/foo/broken"
        value: "HELLO"
      - key: "/foo/test"
        value: "f"
      - key: "/foo/baz"
        valueMap:
          foo: example
          other: thing