apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry-alpha1
  namespace: default
spec:
  refreshInterval: 1m
  target:
   name: foobar
   template:
    engineVersion: v2
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  dataFrom:
    - key: /foo/bar
